-- MySQL Script generated by MySQL Workbench
-- 09/03/16 16:59:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tibico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tibico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tibico` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema tibico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tibico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tibico` DEFAULT CHARACTER SET latin1 ;
USE `tibico` ;

-- -----------------------------------------------------
-- Table `tibico`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`cursos` ;

CREATE TABLE IF NOT EXISTS `tibico`.`cursos` (
  `id_curso` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `regime` VARCHAR(45) NOT NULL,
  `duracao` INT NOT NULL,
  `sigla` VARCHAR(10) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `area_conhecimento` VARCHAR(45) NULL,
  `grau_instrucao` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_curso`),
  UNIQUE INDEX `IdCurso_UNIQUE` (`id_curso` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tibico`.`disciplinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`disciplinas` ;

CREATE TABLE IF NOT EXISTS `tibico`.`disciplinas` (
  `id_disciplina` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `num_creditos` INT NOT NULL,
  `perido_correspondente` INT NOT NULL,
  `area_disciplina` VARCHAR(45) NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_disciplina`),
  UNIQUE INDEX `IdDisciplina_UNIQUE` (`id_disciplina` ASC),
  INDEX `fk_Disciplina_Curso1_idx` (`id_curso` ASC),
  CONSTRAINT `fk_Disciplina_Curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `tibico`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tibico`.`calendarios_academicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`calendarios_academicos` ;

CREATE TABLE IF NOT EXISTS `tibico`.`calendarios_academicos` (
  `id_calendario` INT NOT NULL,
  `identifcador` VARCHAR(20) NULL,
  `duracao` INT NULL,
  `data_inicio_ca` DATETIME NULL,
  `data_inicio_pm` DATETIME NULL,
  `data_fim_pm` DATETIME NULL,
  `data_inicio_pl` DATETIME NULL,
  `data_fim_pl` DATETIME NULL,
  `data_fim_ca` DATETIME NULL,
  `situacao` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_calendario`),
  UNIQUE INDEX `IdCalendario_UNIQUE` (`id_calendario` ASC),
  UNIQUE INDEX `Identifcador_UNIQUE` (`identifcador` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tibico`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `tibico`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `data_nascimento` DATE NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `identidade` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `endereco` TEXT NULL DEFAULT NULL,
  `telefone` VARCHAR(11) NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `ativado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `login` (`login` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tibico`.`professores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`professores` ;

CREATE TABLE IF NOT EXISTS `tibico`.`professores` (
  `id_professor` INT NOT NULL,
  `formacao_academica` VARCHAR(255) NULL,
  `area_atuacao` VARCHAR(255) NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_professor`),
  UNIQUE INDEX `IdProfessor_UNIQUE` (`id_professor` ASC),
  INDEX `fk_Professor_Usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_Professor_Usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tibico`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tibico`.`turmas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`turmas` ;

CREATE TABLE IF NOT EXISTS `tibico`.`turmas` (
  `id_turma` INT NOT NULL,
  `num_vagas` INT NOT NULL,
  `situacao` TINYINT(1) NOT NULL,
  `id_disciplina` INT NOT NULL,
  `id_calendario` INT NOT NULL,
  `id_professor` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  UNIQUE INDEX `IdTruma_UNIQUE` (`id_turma` ASC),
  INDEX `fk_Truma_Disciplina1_idx` (`id_disciplina` ASC),
  INDEX `fk_Truma_CalendarioAcademico1_idx` (`id_calendario` ASC),
  INDEX `fk_Truma_Professor1_idx` (`id_professor` ASC),
  CONSTRAINT `fk_Truma_Disciplina1`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `tibico`.`disciplinas` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Truma_CalendarioAcademico1`
    FOREIGN KEY (`id_calendario`)
    REFERENCES `tibico`.`calendarios_academicos` (`id_calendario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Truma_Professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `tibico`.`professores` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tibico`.`horarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`horarios` ;

CREATE TABLE IF NOT EXISTS `tibico`.`horarios` (
  `id_horario` INT NOT NULL,
  `dia_semana` VARCHAR(45) NOT NULL,
  `horario_inicio` VARCHAR(45) NOT NULL,
  `horario_fim` VARCHAR(45) NOT NULL,
  `id_turma` INT NOT NULL,
  PRIMARY KEY (`id_horario`),
  INDEX `fk_Horario_Truma1_idx` (`id_turma` ASC),
  CONSTRAINT `fk_Horario_Truma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `tibico`.`turmas` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tibico`.`alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`alunos` ;

CREATE TABLE IF NOT EXISTS `tibico`.`alunos` (
  `id_aluno` INT NOT NULL,
  `matricula` VARCHAR(20) NOT NULL,
  `nome_pai` VARCHAR(255) NULL,
  `nome_mae` VARCHAR(255) NULL,
  `situacao` TINYINT(1) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  UNIQUE INDEX `IdAluno_UNIQUE` (`id_aluno` ASC),
  UNIQUE INDEX `Matricula_UNIQUE` (`matricula` ASC),
  INDEX `fk_Aluno_Usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_Aluno_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tibico`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tibico`.`alunos_turmas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`alunos_turmas` ;

CREATE TABLE IF NOT EXISTS `tibico`.`alunos_turmas` (
  `id_aluno` INT NOT NULL,
  `is_turma` INT NOT NULL,
  `frquencia_final` INT NULL,
  `nota_final` INT NULL,
  `situacao_aprovacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_aluno`, `is_turma`),
  INDEX `fk_AlunoTurma_Turma1_idx` (`is_turma` ASC),
  CONSTRAINT `fk_AlunoTurma_Aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `tibico`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AlunoTurma_Turma1`
    FOREIGN KEY (`is_turma`)
    REFERENCES `tibico`.`turmas` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tibico`.`pre_requesitos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`pre_requesitos` ;

CREATE TABLE IF NOT EXISTS `tibico`.`pre_requesitos` (
  `id_disciplina` INT NOT NULL,
  `id_disciplina_requisito` INT NOT NULL,
  PRIMARY KEY (`id_disciplina`, `id_disciplina_requisito`),
  INDEX `fk_PreRequesito_Disciplina2_idx` (`id_disciplina_requisito` ASC),
  CONSTRAINT `fk_PreRequesito_Disciplina1`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `tibico`.`disciplinas` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PreRequesito_Disciplina2`
    FOREIGN KEY (`id_disciplina_requisito`)
    REFERENCES `tibico`.`disciplinas` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tibico`.`avaliacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`avaliacoes` ;

CREATE TABLE IF NOT EXISTS `tibico`.`avaliacoes` (
  `id_avaliacao` INT NOT NULL,
  `tipo_avaliacao` VARCHAR(45) NOT NULL,
  `peso` DECIMAL NOT NULL,
  `data` DATETIME NOT NULL,
  `nota` DECIMAL NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `id_turma` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao`),
  INDEX `fk_Avaliacao_Turma1_idx` (`id_turma` ASC),
  CONSTRAINT `fk_Avaliacao_Turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `tibico`.`turmas` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tibico`.`aulas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`aulas` ;

CREATE TABLE IF NOT EXISTS `tibico`.`aulas` (
  `id_aula` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `quantidade_aulas` INT NOT NULL,
  `conteudo` MEDIUMTEXT NULL,
  `id_turma` INT NOT NULL,
  PRIMARY KEY (`id_aula`),
  UNIQUE INDEX `IdAula_UNIQUE` (`id_aula` ASC),
  INDEX `fk_Aula_Turma1_idx` (`id_turma` ASC),
  CONSTRAINT `fk_Aula_Turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `tibico`.`turmas` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tibico`.`frequencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`frequencias` ;

CREATE TABLE IF NOT EXISTS `tibico`.`frequencias` (
  `id_aula` INT NOT NULL,
  `id_aluno` INT NOT NULL,
  `num_faltas` INT NULL,
  PRIMARY KEY (`id_aula`, `id_aluno`),
  INDEX `fk_Frequencia_Aluno1_idx` (`id_aluno` ASC),
  CONSTRAINT `fk_Frequencia_Aula1`
    FOREIGN KEY (`id_aula`)
    REFERENCES `tibico`.`aulas` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Frequencia_Aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `tibico`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tibico`.`resultados_avaliacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tibico`.`resultados_avaliacoes` ;

CREATE TABLE IF NOT EXISTS `tibico`.`resultados_avaliacoes` (
  `id_avaliacao` INT NOT NULL,
  `id_aluno` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao`, `id_aluno`),
  INDEX `fk_ResultadoAvaliacao_Aluno1_idx` (`id_aluno` ASC),
  CONSTRAINT `fk_ResultadoAvaliacao_Avaliacao1`
    FOREIGN KEY (`id_avaliacao`)
    REFERENCES `tibico`.`avaliacoes` (`id_avaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ResultadoAvaliacao_Aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `tibico`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `tibico` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
